name: smart_mauzo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.5.5
  connectivity_plus: ^6.1.0
  supabase_flutter: ^2.8.0
  barcode_scanner: ^6.1.1
  uuid: ^4.5.1
  intl: ^0.17.0
  charts_flutter: ^0.12.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/scan.png
    - assets/icons/sales.png
    - assets/icons/profile.png